"""create lca

Revision ID: 20240918094431
Revises: 20240918094321
Create Date: 2024-09-18 11:44:31.743811

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20240918094431"
down_revision = "20240918094321"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lca",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lca_created_at"), "lca", ["created_at"], unique=False)
    op.create_index(op.f("ix_lca_name"), "lca", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lca_name"), table_name="lca")
    op.drop_index(op.f("ix_lca_created_at"), table_name="lca")
    op.drop_table("lca")
    # ### end Alembic commands ###
