"""create source

Revision ID: 20240918094255
Revises: 20240916175201
Create Date: 2024-09-18 11:42:55.726413

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20240918094255"
down_revision = "20240916175201"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_name", sa.String(length=64), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("db_version", sa.DECIMAL(5, 2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_source_created_at"), "source", ["created_at"], unique=False)
    op.create_index(op.f("ix_source_db_version"), "source", ["db_version"], unique=False)
    op.create_index(op.f("ix_source_source_name"), "source", ["source_name"], unique=False)
    op.create_index(op.f("ix_source_source_type"), "source", ["source_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_source_type"), table_name="source")
    op.drop_index(op.f("ix_source_source_name"), table_name="source")
    op.drop_index(op.f("ix_source_db_version"), table_name="source")
    op.drop_index(op.f("ix_source_created_at"), table_name="source")
    op.drop_table("source")
    # ### end Alembic commands ###
