"""create impact

Revision ID: 20240918094321
Revises: 20240918094300
Create Date: 2024-09-18 11:43:21.891459

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20240918094321"
down_revision = "20240918094300"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "impact",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("value", sa.DECIMAL(precision=10, scale=6), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_impact_created_at"), "impact", ["created_at"], unique=False)
    op.create_index(op.f("ix_impact_source_id"), "impact", ["source_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_impact_source_id"), table_name="impact")
    op.drop_index(op.f("ix_impact_created_at"), table_name="impact")
    op.drop_table("impact")
    # ### end Alembic commands ###
