"""create phase

Revision ID: 20240916175201
Revises: 20240916175018
Create Date: 2024-09-16 19:50:18.678819

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20240916175201"
down_revision = "20240916175018"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        sa.table(
            "phase_group",
            sa.column("id", sa.Integer),
            sa.column("sort_order", sa.Integer),
            sa.column("name", sa.String),
        ),
        [
            {"id": 1, "sort_order": 1, "name": "Producción"},
            {"id": 2, "sort_order": 2, "name": "Construcción"},
            {"id": 3, "sort_order": 3, "name": "Uso"},
            {"id": 4, "sort_order": 4, "name": "Fin de Vida"},
        ],
    )
    op.bulk_insert(
        sa.table(
            "phase",
            sa.column("id", sa.Integer),
            sa.column("group_id", sa.Integer),
            sa.column("code", sa.String),
            sa.column("name", sa.String),
        ),
        [
            {"code": "A1", "name": "Extracción de materia prima", "group_id": 1},
            {"code": "A2", "name": "Transporte", "group_id": 1},
            {"code": "A3", "name": "Manufacturación", "group_id": 1},
            {"code": "A4", "name": "Transporte", "group_id": 2},
            {"code": "A5", "name": "Instalación", "group_id": 2},
            {"code": "B1", "name": "Uso", "group_id": 3},
            {"code": "B2", "name": "Mantenimiento", "group_id": 3},
            {"code": "B3", "name": "Reparación", "group_id": 3},
            {"code": "B4", "name": "Sustitución", "group_id": 3},
            {"code": "B5", "name": "Rehabilitación", "group_id": 3},
            {"code": "B6", "name": "Consumo de energía", "group_id": 3},
            {"code": "B7", "name": "Consumo de Agua", "group_id": 3},
            {"code": "C1", "name": "Deconstrucción / Demolición", "group_id": 4},
            {"code": "C2", "name": "Transporte", "group_id": 4},
            {"code": "C3", "name": "Tratamiento de los residuos", "group_id": 4},
            {"code": "C4", "name": "Vertido de los residuos", "group_id": 4},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM phase")
    op.execute("DELETE FROM phase_group")
    # ### end Alembic commands ###
