"""populate source

Revision ID: 20240918094300
Revises: 20240918094255
Create Date: 2024-09-18 11:43:21.891459

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20240918094300"
down_revision = "20240918094255"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        sa.table(
            "source",
            sa.column("id", sa.UUID),
            sa.column("source_name", sa.String),
            sa.column("source_type", sa.String),
            sa.column("db_version", sa.DECIMAL),
        ),
        [
            {
                "id": "9639a44f-1269-4f28-b391-e173784719ff",
                "source_name": "source_name_1",
                "source_type": "source_type_1",
                "db_version": 0.01,
            },
            {
                "id": "056cf164-9f13-44ae-b85c-cc4c475e36c5",
                "source_name": "source_name_2",
                "source_type": "source_type_2",
                "db_version": 0.45,
            },
            {
                "id": "7fdb3aad-b232-48dc-86f0-b06af67a45b7",
                "source_name": "source_name_3",
                "source_type": "source_type_3",
                "db_version": 1.82,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM source")
    # ### end Alembic commands ###
