"""populate impact

Revision ID: 20240918094400
Revises: 20240918094321
Create Date: 2024-09-18 11:44:31.743811

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20240918094400"
down_revision = "20240918094321"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        sa.table(
            "impact",
            sa.column("id", sa.UUID),
            sa.column("value", sa.DECIMAL),
            sa.column("category", sa.String),
            sa.column("source_id", sa.UUID),
        ),
        [
            {
                "id": "7cd3b434-b941-454e-b1b6-03e7dac07a3f",
                "value": 123.45,
                "category": "category_1",
                "source_id": "9639a44f-1269-4f28-b391-e173784719ff",
            },
            {
                "id": "58a763f3-233a-48bb-a589-974d420f0811",
                "value": 67.435,
                "category": "category_2",
                "source_id": "9639a44f-1269-4f28-b391-e173784719ff",
            },
            {
                "id": "399ef750-4b0e-404a-8ad2-5b22b7ad20ab",
                "value": 0.41235,
                "category": "category_3",
                "source_id": "9639a44f-1269-4f28-b391-e173784719ff",
            },
            {
                "id": "9602db8e-e6b5-4e05-985d-f417b14c242a",
                "value": 0.000331,
                "category": "category_4",
                "source_id": "9639a44f-1269-4f28-b391-e173784719ff",
            },
            {
                "id": "6110ed07-85cb-45dd-a927-40d9f8d2c38d",
                "value": 9.58490,
                "category": "category_5",
                "source_id": "9639a44f-1269-4f28-b391-e173784719ff",
            },
            {
                "id": "75e1f2f1-2a94-482e-a666-48546d5e2e30",
                "value": 0.01,
                "category": "category_6",
                "source_id": "9639a44f-1269-4f28-b391-e173784719ff",
            },
            {
                "id": "62b32e69-26b9-423d-9d23-57f4c49ea9c1",
                "value": 1.00001,
                "category": "category_7",
                "source_id": "056cf164-9f13-44ae-b85c-cc4c475e36c5",
            },
            {
                "id": "638b8b7d-a496-4ccc-aee0-6f3565d486e1",
                "value": 1024.999999,
                "category": "category_8",
                "source_id": "056cf164-9f13-44ae-b85c-cc4c475e36c5",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM impact")
    # ### end Alembic commands ###
