"""create phase

Revision ID: 20240916175018
Revises:
Create Date: 2024-09-16 19:50:18.678819

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20240916175018"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phase_group",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sort_order", sa.Integer, nullable=False, server_default="0"),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_phase_group_created_at"), "phase_group", ["created_at"], unique=False)
    op.create_index(op.f("ix_phase_group_name"), "phase_group", ["name"], unique=False)
    op.create_table(
        "phase",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["phase_group.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_phase_code"), "phase", ["code"], unique=False)
    op.create_index(op.f("ix_phase_created_at"), "phase", ["created_at"], unique=False)
    op.create_index(op.f("ix_phase_group_id"), "phase", ["group_id"], unique=False)
    op.create_index(op.f("ix_phase_name"), "phase", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_phase_name"), table_name="phase")
    op.drop_index(op.f("ix_phase_group_id"), table_name="phase")
    op.drop_index(op.f("ix_phase_created_at"), table_name="phase")
    op.drop_index(op.f("ix_phase_code"), table_name="phase")
    op.drop_table("phase")
    op.drop_index(op.f("ix_phase_group_name"), table_name="phase_group")
    op.drop_index(op.f("ix_phase_group_created_at"), table_name="phase_group")
    op.drop_table("phase_group")
    # ### end Alembic commands ###
