"""create lca component

Revision ID: 20240918094447
Revises: 20240918094431
Create Date: 2024-09-18 11:44:48.125244

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20240918094447"
down_revision = "20240918094431"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lca_component",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("lca_id", sa.UUID(), nullable=False),
        sa.Column("phase_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("quantity", sa.DECIMAL(precision=12, scale=6), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lca_id"],
            ["lca.id"],
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["lca_component.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["phase_id"], ["phase.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lca_component_created_at"), "lca_component", ["created_at"], unique=False)
    op.create_index(op.f("ix_lca_component_name"), "lca_component", ["name"], unique=False)
    op.create_index(op.f("ix_lca_component_parent_id"), "lca_component", ["parent_id"], unique=False)
    op.create_index(op.f("ix_lca_component_phase_id"), "lca_component", ["phase_id"], unique=False)
    op.create_index(op.f("ix_lca_component_source_id"), "lca_component", ["source_id"], unique=False)
    op.create_index(op.f("ix_lca_component_unit"), "lca_component", ["unit"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lca_component_unit"), table_name="lca_component")
    op.drop_index(op.f("ix_lca_component_source_id"), table_name="lca_component")
    op.drop_index(op.f("ix_lca_component_phase_id"), table_name="lca_component")
    op.drop_index(op.f("ix_lca_component_parent_id"), table_name="lca_component")
    op.drop_index(op.f("ix_lca_component_name"), table_name="lca_component")
    op.drop_index(op.f("ix_lca_component_created_at"), table_name="lca_component")
    op.drop_table("lca_component")
    # ### end Alembic commands ###
